### PR TITLE
Add support for pnpm

### PR DESCRIPTION
**Pull request by g-plane**
**Changes proposed in this pull request:**

Support [pnpm](https://pnpm.io/) for installing front-end dependencies.

**Reviewers should focus on:**

Probably no.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Review by davwheat — COMMENTED** [review]
I wouldn't like this method because it uses `--frozen-lockfile` exclusively for any other arbitrary input. Could we add a `pnpm` clause instead?

We also need to keep the `set +e/-e` otherwise yarn installs may fail.

**Comment by g-plane** [comment]
`pnpm` also supports `--frozen-lockfile` option.

And, actually Yarn is included in the `node` Docker image, we can skip installing it.

**Comment by davwheat** [comment]
> `pnpm` also supports `--frozen-lockfile` option.

I'm aware, but I'd like to separate the processes for Yarn, NPM and pnpm into separate code blocks rather than re-using one block for pnpm and Yarn, in case a future update to one of these deprecates this option, for example, and we have to use a different CLI option to not allow lockfile changes.

> And, actually Yarn is included in the `node` Docker image, we can skip installing it.

Yes, but this doesn't skip that, and will currently cause the action to fail since `npm i -g yarn` will error as `yarn` is already present in `/usr/local/bin` from the docker image. We need `set +e`/`-e` to prevent this, or we could check if `/usr/local/bin/$INPUT_PACKAGE_MANAGER` exists on disk instead (which might be a safer option).

See this workflow run as an example of what I mean: https://github.com/blomstra/flarum-ext-user-filter/runs/5084616739?check_suite_focus=true#step:6:35

Currently this failure is ignored, but with your changes to remove exit on error disabling, this would fail the run.

**Comment by g-plane** [comment]
So can we just skip installing Yarn?

**Comment by davwheat** [comment]
Yes.

**Review by askvortsov1 — APPROVED** [review]
LGTM! Although slight nitpick: can we add a comment saying yarn is already installed so it's clear why it's not there?

**Review by davwheat — APPROVED** [review]

**Pull request merged**
